### ISSUE TITLE
Trying to use in WordPress

### ISSUE THREAD

**Issue by srikat** [antkiewicz/tickerscrambler#1]
Hello,

I have enqueued the js files so they appear like this in the HTML output:

```
<script type='text/javascript' src='http://minimum-pro-copy.dev/wp-content/themes/minimum-pro/js/tickerscrambler.min.js?ver=0.1.1'></script>
<script type='text/javascript' src='http://minimum-pro-copy.dev/wp-content/themes/minimum-pro/js/tickerscrambler.init.js?ver=1.0.0'></script>
```

tickerscrambler.init.js has:

```
jQuery(function( $ ){

    $('.ticker').TickerScrambler({
        list: ['One','Two','Three']
    });

});
```

In the HTML I have:

`<p class="site-description">NOT Just another <span class="ticker">WordPress</span> site</p>`

But there's no "tickering" action going on.

Any ideas?

**Comment by antkiewicz** [comment]
Are there any errors in browser's console? Which version of jQuery are you using this with?

**Comment by srikat** [comment]
Yes.

> Uncaught TypeError: Cannot read property 'fn' of undefined
> Uncaught TypeError: $(...).TickerScrambler is not a function

http://d.pr/i/1ifeQ

Version of jQuery is the one that WordPress comes bundled with: v1.11.3.

Here's some info about jQuery in WordPress: https://codex.wordpress.org/Function_Reference/wp_enqueue_script

Thanks in advance.

**Comment by antkiewicz** [comment]
Fixed. Check version 0.1.2

**Comment by srikat** [comment]
Thanks, works now.
